enum states
{
	normal,
	revolver,
	dynamite,
	boots,
	grabbed,
	tumble,
	finishingblow,
	ejected,
	transition,
	fireass,
	firemouth,
	mort,
	mortjump,
	mortattack,
	morthook,
	hook,
	ghost,
	ghostpossess,
	titlescreen,
	hookshot,
	tacklecharge,
	cheeseball,
	cheeseballclimbwall,
	slap,
	cheesepep,
	cheesepepstick,
	cheesepepjump,
	cheesepepfling,
	cheesepeplaunch,
	cheesepepstickside,
	cheesepepstickup,
	rideweenie,
	motorcycle,
	boxxedpep,
	boxxedpepspin,
	boxxedpepjump,
	pistolaim,
	climbwall,
	knightpepslopes,
	portal,
	secondjump,
	chainsawbump,
	handstandjump,
	lungeattack,
	lungegrab,
	dashtumble,
	gottreasure,
	knightpep,
	knightpepattack,
	knightpepbump,
	meteorpep,
	bombpep,
	bombgrab,
	bombpepside,
	bombpepup,
	grabbing,
	chainsawpogo,
	shotgunjump,
	pogo,
	stunned,
	highjump,
	chainsaw,
	facestomp,
	mach4, // doesnt exist
	timesup,
	machroll,
	shotgun,
	shotguncrouch,
	shotguncrouchjump,
	shotgunshoot,
	shotgundash,
	shotgunfreefall,
	pistol,
	machfreefall,
	throwing,
	slam,
	superslam,
	skateboard,
	grind,
	grab,
	punch,
	backkick,
	uppunch,
	shoulder,
	backbreaker,
	graffiti,
	bossdefeat,
	pizzathrow,
	bossintro,
	gameover,
	keyget,
	tackle,
	jump,
	ladder,
	slipnslide,
	comingoutdoor,
	smirk,
	Sjump,
	victory,
	Sjumpprep,
	crouch,
	crouchjump,
	crouchslide,
	mach1,
	mach2,
	machslide,
	bump,
	hurt,
	freefall,
	hang,
	turning, // doesnt exist
	freefallland,
	door,
	barrel,
	barreljump,
	barrelclimbwall,
	barrelslide,
	current,
	boulder,
	taxi,
	runonball,
	mach3,
	freefallprep,
	Sjumpland,
	faceplant,
	rage,
	idle,
	bounce,
	charge,
	pizzagoblinthrow,
	turn,
	hitceiling, // doesnt exist
	hitwall, // doesnt exist
	groundpoundland,
	walk,
	fall,
	land,
	hit,
	stun,
	recovery, // doesnt exist
	stomped, // doesnt exist
	chase,
	spawnenemy,
	arena,
	arenaintro,
	arenaround,
	actor,
	parry,
	golf,
	float,
	tube,
	UNKNOWN_1, // 151
	policetaxi,
	shoulderbash,
	pummel,
	staggered,
	thrown,
	supershoulderbash,
	superattackstart,
	superattackcharge,
	superattack,
	shoulderturn,
	fistmatch,
	fistmatchend,
	groundpunchstart,
	slipbanan,
	millionpunch,
	skateboardturn,
	bombkick,
	bombpogo,
	jetpackstart,
	jetpack,
	jetpackcancel,
	jetpackspin,
	shield,
	helicopterhat,
	panicjump,
	smokebombstart,
	smokebombcrawl,
	springshoes,
	cardboard,
	cardboardend,
	mockery,
	bombdelete,
	rocket,
	rocketslide,
	gotoplayer,
	trickjump,
	totem,
	underground,
	ridecow,
	ratmount,
	ratmountjump,
	ratmountattack,
	ratmountspit,
	ratmountclimbwall,
	ratmounthurt,
	ratmountgroundpound,
	ratmountbounce,
	UNKNOWN_2, // 199
	ratmountballoon,
	ratmounttumble,
	ratmountgrind,
	ratmounttrickjump,
	ratmountskid,
	ratgrabbed,
	blockstance,
	balloon,
	debugstate,
	trashjumpprep,
	trashjump,
	trashroll,
	stringfling,
	stringjump,
	stringfall,
	noisejetpack,
	spiderweb,
	robotidle,
	robotintro,
	robotroaming,
	robotchase,
	robotinvestigate,
	robotseeking,
	flushidle,
	flushtransition,
	animatronic,
	pizzaface_moustache,
	pizzaface_mouth,
	pizzaface_eyes,
	pizzaface_nose,
	pizzaface_ram,
	pizzaface_phase2transition,
	pizzahead_look,
	pizzahead_fishing,
	UNKNOWN_3, // 234
	pizzahead_bombrun,
	pizzahead_npcthrow,
	pizzahead_portraitthrow,
	pizzahead_enguarde,
	pizzahead_sexypicture,
	pizzahead_pullinglevel,
	pizzahead_eat,
	pizzahead_surprisebox,
	pizzahead_spinningrun,
	pizzahead_spinningkick,
	pizzahead_spinningpunch,
	pizzahead_groundpunch,
	pizzahead_bigkick,
	pizzahead_slamhead,
	pizzahead_slamhead2,
	tv_whitenoise,
	tv_expression,
	playersuperattack,
	UNKNOWN_4, // 253
	jetpackjump,
	UNKNOWN_5, // 255
	UNKNOWN_6, // 256
	bee,
	bee_chase,
	ratmountpunch,
	ratmountcrouch,
	ratmountladder,
	supergrab,
	UNKNOWN_7, // 263
	magnet,
	antigrav,
	secret,
	contemplate,
	mini,
	reloading,
	estampede,
	dropstart,
	drop,
	phase1hurt,
	duel,
	deformed,
	grabdash,
	grabthrow,
	wait,
	flamethrower,
	machinegun,
	bazooka,
	crate,
	noisecrusher,
	droptrap,
	skateboardnoise,
	noiseballooncrash,
	swinging,
	stomp,
	ending,
	backtohub,
	johnghost,
	spaceshuttle,
	animation,
	pizzaheadjump,
	fightball,
	secretenter,
	teleport,
	KO,
	camera_followtarget,
	UNKNOWN_8, // 300
	UNKNOWN_9, // 301
	UNKNOWN_10, // 302
	UNKNOWN_11, // 303, used by obj_stickhat
	UNKNOWN_12, // 304
	machcancelstart,
	machcancel
}

function scr_states()
{
	return
	{
		normal: states.normal,
		revolver: states.revolver,
		dynamite: states.dynamite,
		boots: states.boots,
		grabbed: states.grabbed,
		tumble: states.tumble,
		finishingblow: states.finishingblow,
		ejected: states.ejected,
		transition: states.transition,
		fireass: states.fireass,
		firemouth: states.firemouth,
		mort: states.mort,
		mortjump: states.mortjump,
		mortattack: states.mortattack,
		morthook: states.morthook,
		hook: states.hook,
		ghost: states.ghost,
		ghostpossess: states.ghostpossess,
		titlescreen: states.titlescreen,
		hookshot: states.hookshot,
		tacklecharge: states.tacklecharge,
		cheeseball: states.cheeseball,
		cheeseballclimbwall: states.cheeseballclimbwall,
		slap: states.slap,
		cheesepep: states.cheesepep,
		cheesepepstick: states.cheesepepstick,
		cheesepepjump: states.cheesepepjump,
		cheesepepfling: states.cheesepepfling,
		cheesepeplaunch: states.cheesepeplaunch,
		cheesepepstickside: states.cheesepepstickside,
		cheesepepstickup: states.cheesepepstickup,
		rideweenie: states.rideweenie,
		motorcycle: states.motorcycle,
		boxxedpep: states.boxxedpep,
		boxxedpepspin: states.boxxedpepspin,
		boxxedpepjump: states.boxxedpepjump,
		pistolaim: states.pistolaim,
		climbwall: states.climbwall,
		knightpepslopes: states.knightpepslopes,
		portal: states.portal,
		secondjump: states.secondjump,
		chainsawbump: states.chainsawbump,
		handstandjump: states.handstandjump,
		lungeattack: states.lungeattack,
		lungegrab: states.lungegrab,
		dashtumble: states.dashtumble,
		gottreasure: states.gottreasure,
		knightpep: states.knightpep,
		knightpepattack: states.knightpepattack,
		knightpepbump: states.knightpepbump,
		meteorpep: states.meteorpep,
		bombpep: states.bombpep,
		bombgrab: states.bombgrab,
		bombpepside: states.bombpepside,
		bombpepup: states.bombpepup,
		grabbing: states.grabbing,
		chainsawpogo: states.chainsawpogo,
		shotgunjump: states.shotgunjump,
		pogo: states.pogo,
		stunned: states.stunned,
		highjump: states.highjump,
		chainsaw: states.chainsaw,
		facestomp: states.facestomp,
		mach4: states.mach4, // doesnt exist
		timesup: states.timesup,
		machroll: states.machroll,
		shotgun: states.shotgun,
		shotguncrouch: states.shotguncrouch,
		shotguncrouchjump: states.shotguncrouchjump,
		shotgunshoot: states.shotgunshoot,
		shotgundash: states.shotgundash,
		shotgunfreefall: states.shotgunfreefall,
		pistol: states.pistol,
		machfreefall: states.machfreefall,
		throwing: states.throwing,
		slam: states.slam,
		superslam: states.superslam,
		skateboard: states.skateboard,
		grind: states.grind,
		grab: states.grab,
		punch: states.punch,
		backkick: states.backkick,
		uppunch: states.uppunch,
		shoulder: states.shoulder,
		backbreaker: states.backbreaker,
		graffiti: states.graffiti,
		bossdefeat: states.bossdefeat,
		pizzathrow: states.pizzathrow,
		bossintro: states.bossintro,
		gameover: states.gameover,
		keyget: states.keyget,
		tackle: states.tackle,
		jump: states.jump,
		ladder: states.ladder,
		slipnslide: states.slipnslide,
		comingoutdoor: states.comingoutdoor,
		smirk: states.smirk,
		Sjump: states.Sjump,
		victory: states.victory,
		Sjumpprep: states.Sjumpprep,
		crouch: states.crouch,
		crouchjump: states.crouchjump,
		crouchslide: states.crouchslide,
		mach1: states.mach1,
		mach2: states.mach2,
		machslide: states.machslide,
		bump: states.bump,
		hurt: states.hurt,
		freefall: states.freefall,
		hang: states.hang,
		turning: states.turning, // doesnt exist
		freefallland: states.freefallland,
		door: states.door,
		barrel: states.barrel,
		barreljump: states.barreljump,
		barrelclimbwall: states.barrelclimbwall,
		barrelslide: states.barrelslide,
		current: states.current,
		boulder: states.boulder,
		taxi: states.taxi,
		runonball: states.runonball,
		mach3: states.mach3,
		freefallprep: states.freefallprep,
		Sjumpland: states.Sjumpland,
		faceplant: states.faceplant,
		rage: states.rage,
		idle: states.idle,
		bounce: states.bounce,
		charge: states.charge,
		pizzagoblinthrow: states.pizzagoblinthrow,
		turn: states.turn,
		hitceiling: states.hitceiling, // doesnt exist
		hitwall: states.hitwall, // doesnt exist
		groundpoundland: states.groundpoundland,
		walk: states.walk,
		fall: states.fall,
		land: states.land,
		hit: states.hit,
		stun: states.stun,
		recovery: states.recovery, // doesnt exist
		stomped: states.stomped, // doesnt exist
		chase: states.chase,
		spawnenemy: states.spawnenemy,
		arena: states.arena,
		arenaintro: states.arenaintro,
		arenaround: states.arenaround,
		actor: states.actor,
		parry: states.parry,
		golf: states.golf,
		float: states.float,
		tube: states.tube,
		UNKNOWN_1: states.UNKNOWN_1, // 151
		policetaxi: states.policetaxi,
		shoulderbash: states.shoulderbash,
		pummel: states.pummel,
		staggered: states.staggered,
		thrown: states.thrown,
		supershoulderbash: states.supershoulderbash,
		superattackstart: states.superattackstart,
		superattackcharge: states.superattackcharge,
		superattack: states.superattack,
		shoulderturn: states.shoulderturn,
		fistmatch: states.fistmatch,
		fistmatchend: states.fistmatchend,
		groundpunchstart: states.groundpunchstart,
		slipbanan: states.slipbanan,
		millionpunch: states.millionpunch,
		skateboardturn: states.skateboardturn,
		bombkick: states.bombkick,
		bombpogo: states.bombpogo,
		jetpackstart: states.jetpackstart,
		jetpack: states.jetpack,
		jetpackcancel: states.jetpackcancel,
		jetpackspin: states.jetpackspin,
		shield: states.shield,
		helicopterhat: states.helicopterhat,
		panicjump: states.panicjump,
		smokebombstart: states.smokebombstart,
		smokebombcrawl: states.smokebombcrawl,
		springshoes: states.springshoes,
		cardboard: states.cardboard,
		cardboardend: states.cardboardend,
		mockery: states.mockery,
		bombdelete: states.bombdelete,
		rocket: states.rocket,
		rocketslide: states.rocketslide,
		gotoplayer: states.gotoplayer,
		trickjump: states.trickjump,
		totem: states.totem,
		underground: states.underground,
		ridecow: states.ridecow,
		ratmount: states.ratmount,
		ratmountjump: states.ratmountjump,
		ratmountattack: states.ratmountattack,
		ratmountspit: states.ratmountspit,
		ratmountclimbwall: states.ratmountclimbwall,
		ratmounthurt: states.ratmounthurt,
		ratmountgroundpound: states.ratmountgroundpound,
		ratmountbounce: states.ratmountbounce,
		UNKNOWN_2: states.UNKNOWN_2, // 199
		ratmountballoon: states.ratmountballoon,
		ratmounttumble: states.ratmounttumble,
		ratmountgrind: states.ratmountgrind,
		ratmounttrickjump: states.ratmounttrickjump,
		ratmountskid: states.ratmountskid,
		ratgrabbed: states.ratgrabbed,
		blockstance: states.blockstance,
		balloon: states.balloon,
		debugstate: states.debugstate,
		trashjumpprep: states.trashjumpprep,
		trashjump: states.trashjump,
		trashroll: states.trashroll,
		stringfling: states.stringfling,
		stringjump: states.stringjump,
		stringfall: states.stringfall,
		noisejetpack: states.noisejetpack,
		spiderweb: states.spiderweb,
		robotidle: states.robotidle,
		robotintro: states.robotintro,
		robotroaming: states.robotroaming,
		robotchase: states.robotchase,
		robotinvestigate: states.robotinvestigate,
		robotseeking: states.robotseeking,
		flushidle: states.flushidle,
		flushtransition: states.flushtransition,
		animatronic: states.animatronic,
		pizzaface_moustache: states.pizzaface_moustache,
		pizzaface_mouth: states.pizzaface_mouth,
		pizzaface_eyes: states.pizzaface_eyes,
		pizzaface_nose: states.pizzaface_nose,
		pizzaface_ram: states.pizzaface_ram,
		pizzaface_phase2transition: states.pizzaface_phase2transition,
		pizzahead_look: states.pizzahead_look,
		pizzahead_fishing: states.pizzahead_fishing,
		UNKNOWN_3: states.UNKNOWN_3, // 234
		pizzahead_bombrun: states.pizzahead_bombrun,
		pizzahead_npcthrow: states.pizzahead_npcthrow,
		pizzahead_portraitthrow: states.pizzahead_portraitthrow,
		pizzahead_enguarde: states.pizzahead_enguarde,
		pizzahead_sexypicture: states.pizzahead_sexypicture,
		pizzahead_pullinglevel: states.pizzahead_pullinglevel,
		pizzahead_eat: states.pizzahead_eat,
		pizzahead_surprisebox: states.pizzahead_surprisebox,
		pizzahead_spinningrun: states.pizzahead_spinningrun,
		pizzahead_spinningkick: states.pizzahead_spinningkick,
		pizzahead_spinningpunch: states.pizzahead_spinningpunch,
		pizzahead_groundpunch: states.pizzahead_groundpunch,
		pizzahead_bigkick: states.pizzahead_bigkick,
		pizzahead_slamhead: states.pizzahead_slamhead,
		pizzahead_slamhead2: states.pizzahead_slamhead2,
		tv_whitenoise: states.tv_whitenoise,
		tv_expression: states.tv_expression,
		playersuperattack: states.playersuperattack,
		UNKNOWN_4: states.UNKNOWN_4, // 253
		jetpackjump: states.jetpackjump,
		UNKNOWN_5: states.UNKNOWN_5, // 255
		UNKNOWN_6: states.UNKNOWN_6, // 256
		bee: states.bee,
		bee_chase: states.bee_chase,
		ratmountpunch: states.ratmountpunch,
		ratmountcrouch: states.ratmountcrouch,
		ratmountladder: states.ratmountladder,
		supergrab: states.supergrab,
		UNKNOWN_7: states.UNKNOWN_7, // 263
		magnet: states.magnet,
		antigrav: states.antigrav,
		secret: states.secret,
		contemplate: states.contemplate,
		mini: states.mini,
		reloading: states.reloading,
		estampede: states.estampede,
		dropstart: states.dropstart,
		drop: states.drop,
		phase1hurt: states.phase1hurt,
		duel: states.duel,
		deformed: states.deformed,
		grabdash: states.grabdash,
		grabthrow: states.grabthrow,
		wait: states.wait,
		flamethrower: states.flamethrower,
		machinegun: states.machinegun,
		bazooka: states.bazooka,
		crate: states.crate,
		noisecrusher: states.noisecrusher,
		droptrap: states.droptrap,
		skateboardnoise: states.skateboardnoise,
		noiseballooncrash: states.noiseballooncrash,
		swinging: states.swinging,
		stomp: states.stomp,
		ending: states.ending,
		backtohub: states.backtohub,
		johnghost: states.johnghost,
		spaceshuttle: states.spaceshuttle,
		animation: states.animation,
		pizzaheadjump: states.pizzaheadjump,
		fightball: states.fightball,
		secretenter: states.secretenter,
		teleport: states.teleport,
		KO: states.KO,
		camera_followtarget: states.camera_followtarget,
		UNKNOWN_8: states.UNKNOWN_8, // 300
		UNKNOWN_9: states.UNKNOWN_9, // 301
		UNKNOWN_10: states.UNKNOWN_10, // 302
		UNKNOWN_11: states.UNKNOWN_11, // 303, used by obj_stickhat
		UNKNOWN_12: states.UNKNOWN_12, // 304
		machcancelstart: states.machcancelstart,
		machcancel: states.machcancel
	};
}
